/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufo;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.BufferStrategy;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;

/**
 *
 * @author Proprietario
 */
public class JFramejogo extends javax.swing.JFrame implements Runnable{
private Alien nave;
    private boolean fim;
    private ArrayList<Inimigo> inimigos;
    private Planodefundo fundo;
    private Font minhaFonte = new Font("Consolas", Font.BOLD, 20);
    
    public JFramejogo() {
       
        nave = new Alien();
        fim = false;
        inimigos = new ArrayList<Inimigo>();
        fundo = new Planodefundo();
        for(int i=0;i<60;i++){
            inimigos.add(new Inimigo(50 + i%20 * 50, 50 + i/20  * 75,1));
        }
        initComponents();
        createBufferStrategy(2);
        Thread t = new Thread(this);
        t.start();
    } 

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    /**
     * @param args the command line arguments
     */
                              
  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
        JFramejogo janela = new JFramejogo() ;
        janela.setSize(1366, 768);
        janela.setLocationRelativeTo(null);
        //iniciar no centro da tela.
        janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.addKeyListener(true);
        janela.setVisible(true);
            }
        });
      
    }  

      
    @Override
    
    public void run() {
    while(true){
       

     Graphics g;
     BufferStrategy buffer = getBufferStrategy();
    
      
     g = buffer.getDrawGraphics();
    super.paintComponents(g);
      
    fundo.pinta(g);
    nave.pinta(g);
     
      for(int i=0;i<inimigos.size();i++){
         inimigos.get(i).pinta(g);
      }
      
       update();
      
      
      
      	if (fim) {
			g.setColor(Color.white);
			g.setFont(minhaFonte);
			g.drawString("ALIENS EXIST!", 1366/2 - 100, 768/2 );
			
        }
            

            g.dispose();

            //Mostra o desenho
           
            buffer.show();

             try {
                Thread.sleep(5);
            } catch (InterruptedException ex) {
            }
        } 
        }
    private void update(){
   //  nave.mover(tecla);
      for(int i=0;i<inimigos.size();i++){
         
     inimigos.get(i).atualizar();
     
     if(inimigos.get(i).getY() >= 768 -150){
         fim = true;
         
     }
     }
      for(int i=0;i<inimigos.size();i++){
          
         if(inimigos.get(i).getX() <= 0 || inimigos.get(i).getX() >= 1366 - 50){
             for(int j=0;j<inimigos.size();j++){
                 inimigos.get(j).trocadirecao();
             }
             break;
         }
      }
      
    }
    
   

    private void dorme() {
        try {  
            Thread.sleep(20);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFramejogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
